// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {update} from '../models';
import {config} from '../models';
import {gui} from '../models';
import {workflow} from '../models';

export function CheckForUpdate(arg1:boolean):Promise<update.UpdateInfo>;

export function CheckPlexAuth(arg1:number):Promise<string>;

export function CreateSource(arg1:string,arg2:string,arg3:Record<string, string>):Promise<config.Source>;

export function DeleteSource(arg1:string):Promise<void>;

export function DeleteWorkflow(arg1:string):Promise<void>;

export function FixPermissions():Promise<void>;

export function GetPermissionStatus():Promise<string>;

export function GetUpdateConfig():Promise<config.UpdateConfig>;

export function GetVersion():Promise<string>;

export function GetWorkflow(arg1:string):Promise<config.Workflow>;

export function GetWorkflowDiff(arg1:string):Promise<Array<gui.StepDiff>>;

export function InitPlexAuth():Promise<gui.PlexAuthChallenge>;

export function InstallUpdate():Promise<void>;

export function ListSources():Promise<Array<config.Source>>;

export function ListWorkflows():Promise<Array<config.Workflow>>;

export function OpenFileDialog(arg1:string):Promise<string>;

export function PreviewQuery(arg1:string,arg2:string,arg3:string):Promise<gui.QueryResult>;

export function PreviewWorkflow(arg1:string):Promise<workflow.WorkflowResult>;

export function RunWorkflow(arg1:string):Promise<workflow.WorkflowResult>;

export function SaveWorkflow(arg1:config.Workflow):Promise<config.Workflow>;

export function SetUpdateInterval(arg1:number):Promise<void>;

export function UpdateSource(arg1:config.Source):Promise<void>;
