// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSource(arg1, arg2, arg3) {
  return window['go']['gui']['App']['CreateSource'](arg1, arg2, arg3);
}

export function DeleteSource(arg1) {
  return window['go']['gui']['App']['DeleteSource'](arg1);
}

export function DeleteWorkflow(arg1) {
  return window['go']['gui']['App']['DeleteWorkflow'](arg1);
}

export function GetWorkflow(arg1) {
  return window['go']['gui']['App']['GetWorkflow'](arg1);
}

export function GetWorkflowDiff(arg1) {
  return window['go']['gui']['App']['GetWorkflowDiff'](arg1);
}

export function ListSources() {
  return window['go']['gui']['App']['ListSources']();
}

export function ListWorkflows() {
  return window['go']['gui']['App']['ListWorkflows']();
}

export function PreviewWorkflow(arg1) {
  return window['go']['gui']['App']['PreviewWorkflow'](arg1);
}

export function RunWorkflow(arg1) {
  return window['go']['gui']['App']['RunWorkflow'](arg1);
}

export function SaveWorkflow(arg1) {
  return window['go']['gui']['App']['SaveWorkflow'](arg1);
}

export function UpdateSource(arg1) {
  return window['go']['gui']['App']['UpdateSource'](arg1);
}
