// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate(arg1) {
  return window['go']['gui']['App']['CheckForUpdate'](arg1);
}

export function CheckPlexAuth(arg1) {
  return window['go']['gui']['App']['CheckPlexAuth'](arg1);
}

export function CreateConnection(arg1, arg2, arg3) {
  return window['go']['gui']['App']['CreateConnection'](arg1, arg2, arg3);
}

export function DeleteConnection(arg1) {
  return window['go']['gui']['App']['DeleteConnection'](arg1);
}

export function DeleteWorkflow(arg1) {
  return window['go']['gui']['App']['DeleteWorkflow'](arg1);
}

export function FixPermissions() {
  return window['go']['gui']['App']['FixPermissions']();
}

export function GetPermissionStatus() {
  return window['go']['gui']['App']['GetPermissionStatus']();
}

export function GetUpdateConfig() {
  return window['go']['gui']['App']['GetUpdateConfig']();
}

export function GetVersion() {
  return window['go']['gui']['App']['GetVersion']();
}

export function GetWorkflow(arg1) {
  return window['go']['gui']['App']['GetWorkflow'](arg1);
}

export function GetWorkflowDiff(arg1) {
  return window['go']['gui']['App']['GetWorkflowDiff'](arg1);
}

export function InitPlexAuth() {
  return window['go']['gui']['App']['InitPlexAuth']();
}

export function InstallUpdate() {
  return window['go']['gui']['App']['InstallUpdate']();
}

export function ListConnections() {
  return window['go']['gui']['App']['ListConnections']();
}

export function ListProviders() {
  return window['go']['gui']['App']['ListProviders']();
}

export function ListWorkflows() {
  return window['go']['gui']['App']['ListWorkflows']();
}

export function OpenFileDialog(arg1) {
  return window['go']['gui']['App']['OpenFileDialog'](arg1);
}

export function PreviewQuery(arg1, arg2, arg3) {
  return window['go']['gui']['App']['PreviewQuery'](arg1, arg2, arg3);
}

export function PreviewWorkflow(arg1) {
  return window['go']['gui']['App']['PreviewWorkflow'](arg1);
}

export function RunWorkflow(arg1) {
  return window['go']['gui']['App']['RunWorkflow'](arg1);
}

export function SaveFileDialog(arg1, arg2) {
  return window['go']['gui']['App']['SaveFileDialog'](arg1, arg2);
}

export function SaveWorkflow(arg1) {
  return window['go']['gui']['App']['SaveWorkflow'](arg1);
}

export function SetUpdateInterval(arg1) {
  return window['go']['gui']['App']['SetUpdateInterval'](arg1);
}

export function UpdateConnection(arg1) {
  return window['go']['gui']['App']['UpdateConnection'](arg1);
}
