[tools]
go = "1.25"
python = "3.12"

[tasks]
build-cli = "go build -o bin/  ./cmd/djlt"
build-gui = { run = "wails build", dir = "cmd/djlt-gui" }
gui-dev = { run = "wails dev", dir = "cmd/djlt-gui" }
gui-install = { run = "pnpm install", dir = "cmd/djlt-gui/frontend" }
test = "go test ./..."
fmt = "gofmt -w ."
fmt-check = { run = "test -z \"$(gofmt -l .)\"" }
gen-docs = "go run scripts/gen_docs/main.go"
docs = { depends = ["gen-docs"], run = "pip install -r requirements.txt && mkdocs serve" }
